default_settings:
    trainer_type: ppo
    hyperparameters:
        batch_size: 1024
        buffer_size: 10240  
        learning_rate: 3.0e-4
        beta: 5.0e-3
        epsilon: 0.2
        lambd: 0.95
        num_epoch: 3
        learning_rate_schedule: linear
    network_settings:
        normalize: false
        hidden_units: 128
        num_layers: 2
        vis_encode_type: simple
        memory:
          sequence_length: 64
          memory_size: 256
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    max_steps: 5.0e5
    time_horizon: 64
    summary_freq: 10000

behaviors:
    AircraftLearning:
        hyperparameters:
            batch_size: 2048
            buffer_size: 20480  
            beta: 1.0e-2
        network_settings:
            hidden_units: 256
        max_steps: 5.0e7
        time_horizon: 128
        summary_freq: 10000


# For curriculum
environment_parameters:
  checkpoint_radius:
    curriculum:
        - name: Lesson0 
          completion_criteria:
            measure: reward
            behavior: AircraftLearning
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 0.5
          value: 50.0   # 55
        - name: Lesson1 
          completion_criteria:
            measure: reward
            behavior: AircraftLearning
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 1
          value: 30.0   # 35
        - name: Lesson2 
          completion_criteria:
            measure: reward
            behavior: AircraftLearning
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 1.5
          value: 20.0
        - name: Lesson3 
          completion_criteria:
            measure: reward
            behavior: AircraftLearning
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 2
          value: 10.0
        - name: Lesson4 
          completion_criteria:
            measure: reward
            behavior: AircraftLearning
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 2.5
          value: 0.0