behaviors:
    AircraftLearning:
        trainer_type: ppo
        hyperparameters:
            batch_size: 2048
            buffer_size: 20480  
            learning_rate: 3.0e-4
            beta: 5.0e-4 #1.0e-2
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
        max_steps: 500000
        time_horizon: 64
        summary_freq: 10000
        
        # trainer_type: ppo
        # hyperparameters:
        #     batch_size: 2048
        #     buffer_size: 20480  
        #     learning_rate: 3.0e-4
        #     beta: 1.0e-2
        #     epsilon: 0.2
        #     lambd: 0.95
        #     num_epoch: 3
        #     learning_rate_schedule: linear
        # network_settings:
        #     normalize: false
        #     hidden_units: 256
        #     num_layers: 2
        #     vis_encode_type: simple
        #     memory:
        #       memory_size: 256
        #       sequence_length: 64
        # reward_signals:
        #     extrinsic:
        #         strength: 1.0
        #         gamma: 0.99
        # max_steps: 5.0e7
        # time_horizon: 128
        # summary_freq: 10000


        # use_recurrent: false  

environment_parameters:
  checkpoint_radius:
    curriculum:
        - name: Lesson0 # This is the start of the second lesson
          completion_criteria:
            measure: reward
            behavior: AircraftLearning
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 2.0
          value: 60.0
        - name: Lesson1 # This is the start of the second lesson
          completion_criteria:
            measure: reward
            behavior: AircraftLearning
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 2.0
          value: 35.0
        - name: Lesson2 # This is the start of the second lesson
          completion_criteria:
            measure: reward
            behavior: AircraftLearning
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 4.0
          value: 20.0
        - name: Lesson3 # This is the start of the second lesson
          completion_criteria:
            measure: reward
            behavior: AircraftLearning
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 6.0
          value: 10.0
        - name: Lesson4 # This is the start of the second lesson
          completion_criteria:
            measure: reward
            behavior: AircraftLearning
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 6.0
          value: 0.0